<?php
require 'templates/header.phtml';
?>
<form action="agregar" method="POST" class="my-4">
    <div class="row">
        <div class="col-4">
            <div class="form-group">
                <label>Nombre y Apellido</label>
                <input name="nombre" type="text" class="form-control" placeholder="Nombre y Apellido">
            </div>
        </div>

        <div class="col-4">
            <div class="form-group">
                <label>email</label>
                <input name="email" type="email" class="form-control" placeholder="E-mail">
            </div>
        </div>

        <div class="col-4">
            <div class="form-group">
                <label>materia</label>
                <select name="materia_id" class="form-control">
                    <?php 
                        foreach ($materias as $materia) {
                            
                            echo '<option value=' . $materia->materia_id . '>' . $materia->nombre . '</option>';
                          
                        }
                    ?>
                </select>
            </div>
        </div>
        
    </div>

    <div class="form-group">
        <label>Objetivo</label>
        <textarea name="objetivo" placeholder="Objetivo" class="form-control" rows="3"></textarea>
    </div>

    <button type="submit" class="btn btn-primary mt-2">Agregar</button>
</form>
<?php
require 'templates/footer.phtml';

