<?php
require 'templates/header.phtml';
?>
<form action="agregar" method="POST" class="my-4">
    <div class="row">
        <div class="col-4">
            <div class="form-group">
                <label>Nombre y apellido</label>
                <input name="nombre" type="text" class="form-control">
            </div>
        </div>

        <div class="col-4">
            <div class="form-group">
                <label>email</label>
                <input name="email" type="email" class="form-control">
            </div>
        </div>

        <div class="col-4">
            <div class="form-group">
                <label>materia</label>
                <select name="materia_id" class="form-control">
                    <option value="1">Web 2</option> 
                    <option value="2">Programacion 2</option> 
                    <option value="3">Tecnología de la Información en las Organizaciones</option> 
                    <option value="4">Ingles 2</option> 
                </select>
            </div>
        </div>
        
    </div>

    <div class="form-group">
        <label>Objetivo</label>
        <textarea name="objetivo" class="form-control" rows="3"></textarea>
    </div>

    <button type="submit" class="btn btn-primary mt-2">Agregar</button>
</form>
<?php
require 'templates/footer.phtml';

