<?php
require 'templates/header.phtml';

foreach($materias as $materia){
    if($id==$materia->materia_id){
        ?>
    <table class="table table-striped table-primary">
        <thead>
            <tr>
                <th scope="col">Nombre</th>
                <th scope="col">Profesor</th>
                <th scope="col">Horario</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><?php echo $materia->nombre ?></td>
                <td><?php echo $materia->profesor ?></td>
                <td><?php echo $materia->horario ?></td>
            </tr>
        </tbody>
    </table>
        <?php ;
    }
}
require 'templates/footer.phtml';

