<?php
require 'templates/header.phtml';

foreach($inscripciones as $inscripcion){
    if($id==$inscripcion->inscripcion_id){
        ?>
    <table class="table table-striped table-primary">
        <thead>
            <tr>
                <th scope="col">nombre</th>
                <th scope="col">Email</th>
                <th scope="col">Objetivo</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><?php echo $inscripcion->nombre ?></td>
                <td><?php echo $inscripcion->email ?></td>
                <td><?php echo $inscripcion->objetivo ?></td>

                <td>
                    <a href="eliminar/<?php echo $inscripcion->inscripcion_id ?>">
                        <button type="click" class="btn btn-danger">Borrar</button>
                    </a>
                </td>

                <td>
                    <a href="mostrarEdicion/<?php echo $inscripcion->inscripcion_id ?>">
                    <button type="submit" class="btn btn-primary ml-auto">Modificar</button>
                    </a>
                </td>
            </tr>
        </tbody>
    </table>
        <?php ;
    }
}
require 'templates/footer.phtml';

