<?php
require 'templates/header.phtml';
?>
<ul class="list-group">
        <?php foreach($materias as $materia) { ?>
            <li class="list-group-item item-inscripcion">
                <div>
                    <b><?php echo $materia->nombre ?> </b>
                </div>
                <div class="actions">
                    <a href="filtro/<?php echo $materia->materia_id ?>" type="button" class='btn btn-dark ml-auto'>ver alumnos inscriptos</a>
                    <a href="eliminar_materia/<?php echo $materia->materia_id ?>" type="button" class='btn btn-danger'>eliminar</a>
                    <a href="infoMateria/<?php echo $materia->materia_id ?>" type="button" class='btn btn-primary ml-auto'>ver info</a>
            </li>
        <?php } ?>
        </ul>
<?php
require 'templates/footer.phtml';