<?php
require 'templates/header.phtml';
?>

<ul class="list-group">
<?php 
$contador=0;
foreach($inscripciones as $inscripcion) { 
    if($id==null || $id==$inscripcion->materia_id){?>
        <li class="list-group-item item-inscripcion">
            <div>
                <b><?php echo $inscripcion->nombre ?> | Materia: <?php echo $materias[$inscripcion->materia_id-1]->nombre ?> </b>
            </div>
            <div class="actions">
                <a href="info/<?php echo $inscripcion->inscripcion_id ?>" type="button" class='btn btn-primary ml-auto'>ver info</a>
            </div>
        </li>
        
<?php
    $contador++; }}
    if($contador==0){
        echo "
        <div class='alert alert-danger' role='alert'>
            <p>No hay alumnos inscriptos a esta materia</p>
        </div> 
        ";
    }
?>
</ul>
<?php
require 'templates/footer.phtml';